# Generated by Django 5.1.2 on 2024-10-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_spaces_star_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.CharField(max_length=500)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.spaces')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
