# Generated by Django 5.1.2 on 2024-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_payment_options_payment_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
