# Generated by Django 5.1.2 on 2024-10-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_method',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('FORM', 'FORM')], max_length=20, null=True),
        ),
    ]
