# Generated by Django 5.1.2 on 2024-10-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_signup_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_method',
            field=models.CharField(choices=[('GOOGLE', 'GOOGLE'), ('FORM', 'FORM')], default='FORM', max_length=20),
        ),
    ]
